name: Streamlit app

# Déclencher l'action quand il y a un push sur la branche main
on:
  push:
    branches: ["dev"]


permissions:
  contents: read

jobs:
  streamlit:
    runs-on: ubuntu-latest
    steps:
    - name: GIT commit and push docs
      env: 
        CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
        CI_COMMIT_AUTHOR: Comas Christophe
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "christophe.comas66@gmail.com"
        git mv front.py front_deploy.py
        git commit -m "Rename file"
        git push
