name: Run Pytest and Copy File

# Déclencher l'action quand il y a un push sur la branche main
on:
  push:
    branches:
      - dev

jobs:
  test-and-copy:
    runs-on: ubuntu-latest  # Utilise un environnement Linux

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout the code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Remplace par ta version de Python

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Lancer les tests avec pytest
      - name: Run Pytest
        run: |
          pytest

      # Étape 5 : Si pytest réussit, copier front.py dans le dossier streamlit
      - name: Copy front.py to streamlit folder
        if: success()  # Cette étape s'exécute uniquement si pytest a réussi
        run: |
          cp front.py streamlit/
